import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import Footer from "./Footer";
import Head from 'next/head';
import Bar from "@/app/Bar"  

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Alex Dunn Tours",
  description: "Generated by Gleits",
  icons:{
    icon:['/favicon.ico?v=4']
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/logo.png" />
      </Head>
      <body className={inter.className}>
        {/* <Bar /> */}
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

